dumpsteroverflow/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'dumpsteroverflow.do_core.views.home', name='home'),
    url(r'^overflow/(?P<points>\d+)/$', 'dumpsteroverflow.do_core.views.overflow', name='overflow'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'dumpsteroverflow.do_core.views.login', name='login'),
    url(r'^geo/$', 'dumpsteroverflow.do_core.views.geo', name='geo'),
)
urlpatterns += staticfiles_urlpatterns()

dumpsteroverflow/do_core/models.py
from django.db import models
from django.contrib.auth.models import User


class GenericFieldsMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_on = models.DateTimeField(blank=True, null=True)

    class Meta:
        abstract = True


class Address(GenericFieldsMixin):
    street_address = models.CharField(max_length=200)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=50)

    class Meta:
        unique_together = ('street_address', 'zip_code', 'city')

    def __unicode__(self):
        return u'%s %d %s' %(self.street_address, self.zip_code, self.city)


class Discoverer(GenericFieldsMixin):
    user = models.OneToOneField(User)
    points = models.IntegerField(default=0)
    default_address = models.OneToOneField(Address, null=True)

    def __unicode__(self):
        return u'%s' %self.user.__unicode__()


class Dumpster(GenericFieldsMixin):
    DUMPSTER_TYPES = (
            ('BROWN', 'ORGANIC'),
            ('YELLOW', 'PLASTIC'),
            ('BLUE', 'PAPER'),
            ('GRAY', 'WASTE'),
        )
    DUMPSTER_FIELDS = {
        'is_brown': DUMPSTER_TYPES[0][0],
        'is_yellow': DUMPSTER_TYPES[1][0],
        'is_blue': DUMPSTER_TYPES[2][0],
        'is_gray': DUMPSTER_TYPES[3][0]
    }

    dumpster_type = models.CharField(max_length=10, choices=DUMPSTER_TYPES)
    location = models.ForeignKey(Address)
    is_full = models.BooleanField(default=False)

    class Meta:
        unique_together = ('dumpster_type', 'location')

    def __unicode__(self):
        return u'%s %s' %(self.dumpster_type, self.location.__unicode__())


class Overflow(GenericFieldsMixin):
    user = models.ForeignKey(Discoverer)
    dumpster = models.ForeignKey(Dumpster)

dumpsteroverflow/do_core/forms.py
from django import forms
from models import Dumpster

class OverflowForm(forms.Form):
    is_brown = forms.BooleanField(required=False)
    is_yellow = forms.BooleanField(required=False)
    is_blue = forms.BooleanField(required=False)
    is_gray = forms.BooleanField(required=False)

    street_address = forms.CharField(max_length=200)
    zip_code = forms.IntegerField()
    city = forms.CharField(max_length=50)

dumpsteroverflow/do_core/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse

from forms import OverflowForm
from models import Address, Dumpster, Overflow
from django.views.generic.base import View
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from geopy.geocoders import GoogleV3
import json
import paypalrestsdk as pp
import os


def login(request):
    token = request.GET.get('code')
    pp.configure({
        "mode": os.environ['PAYPAL_MODE'],
        "client_id": os.environ['PAYPAL_CLIENT_ID'],
        "client_secret": os.environ['PAYPAL_CLIENT_SECRET'],
        "openid_redirect_uri": os.environ['PAYPAL_OPENID_REDIRECT_URI']})
    if token:
        user = authenticate(token=token)
        if user is not None:
            auth_login(request, user)
            redirect_url = '/'
    else:
        redirect_url = pp.Tokeninfo.authorize_url({
            "scope": "profile email address phone https://uri.paypal.com/services/paypalattributes",
            })
    return redirect(redirect_url)


@login_required(login_url='login/', redirect_field_name='status')
def home(request):
    template_name = 'home.html'
    form = OverflowForm()

    if request.method == 'POST':
        form = OverflowForm(request.POST)
        if form.is_valid():
            points = 0
            address, created = Address.objects.get_or_create(street_address=form.cleaned_data['street_address'],
                zip_code=form.cleaned_data['zip_code'], city=form.cleaned_data['city'])
            for field, dumpster_type in Dumpster.DUMPSTER_FIELDS.items():
                if form.cleaned_data[field]:
                    dumpster, created = Dumpster.objects.get_or_create(dumpster_type=dumpster_type, location=address)
                    dumpster.dumpster_type = dumpster_type
                    if not dumpster.is_full:
                        dumpster.is_full = True
                        points += 3
                        Overflow.objects.create(user=request.user.discoverer, dumpster=dumpster)
                    dumpster.save()
            request.user.discoverer.points += points
            request.user.discoverer.save()
            return HttpResponseRedirect(reverse('overflow', args=(points,)))
    else:
        address = request.user.discoverer.default_address
        if address:
            formdict = {'city': address.city,
                        'zip_code': address.zip_code,
                        'street_address': address.street_address}
            form = OverflowForm(initial=formdict)

    context = {'form': form}
    return render(request, template_name, context)

def overflow(request, points):
    if points=='0':
        return render(request, 'overflow_sent.html', {'flash_error': 'This dumpster overflow was already reported.'})
    else:
        return render(request, 'overflow_sent.html', {'points': points})

def geo(request):
    lat = request.POST['lat']
    lng = request.POST['lng']
    geolocator = GoogleV3()
    location = geolocator.reverse("{}, {}".format(lat, lng))
    json_data = json.dumps(location.raw)
    return HttpResponse(json_data, mimetype="application/json")

dumpsteroverflow/templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
   <head>
      <meta charset="UTF-8">
      <title>Dumpster Overflow</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static "stylesheets/themes/dumpsteroverflow.min.css" %}" />
      <link rel="stylesheet" href="{% static "stylesheets/themes/jquery.mobile.icons.min.css" %}" />
      <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.2/jquery.mobile.structure-1.4.2.min.css" />
      <link rel="stylesheet" href="{% static "stylesheets/dumpsteroverflow.css" %}" />
      <!--<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>-->
      <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
      <script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>
      {% block extra_js %}{% endblock %}
   </head>
   <body>
      {% block body %}{% endblock %}
   </body>
</html>

dumpsteroverflow/templates/home.html
{% extends "base.html" %}
{% load enhance_markup %}
{% load staticfiles %}

{% block extra_js %}<script src="{% static "js/geolocation.js" %}"></script>{% endblock %}
{% block body %}
<div data-role="page" class="home_page" data-theme="a">

  <div data-role="header">
    <p class="user_info ui-title">
    {% if user.discoverer %}<span class="nb_of_points">{{user.discoverer.points}}</span><span class="trophy"><img src="{% static "stylesheets/themes/images/icons-png/trophy-2.png" %}"></span>{% endif %}
    <span class="user_name">{{user.first_name}}</span>
    </p>
  </div>

  <div role="main" class="ui-content">
    <form method="post">{% csrf_token %}
      <fieldset data-type="horizontal">
        <h3 class="headline">Which dumpsters are full?</h3>
        <div class="ui-grid-b">
          <div class="dumpster_type ui-block-a" >
            <label for="id_is_brown"><img src="{% static "stylesheets/themes/images/icons-png/plant-2.png" %}"></label>
            {{form.is_brown|add_attrs:"data-theme:c"}}
          </div>
          <div class="dumpster_type ui-block-b" >
            <label for="id_is_yellow"><img src="{% static "stylesheets/themes/images/icons-png/coffee.png" %}"></label>
            {{form.is_yellow|add_attrs:"data-theme:d"}}
          </div>
          <div class="dumpster_type ui-block-a" >
            <label for="id_is_blue"><img src="{% static "stylesheets/themes/images/icons-png/stickynote-2.png" %}"></label>
            {{form.is_blue|add_attrs:"data-theme:b"}}
          </div>
          <div class="dumpster_type ui-block-b" >
            <label for="id_is_gray"><img src="{% static "stylesheets/themes/images/icons-png/skull-2.png" %}"></label>
            {{form.is_gray|add_attrs:"data-theme:e"}}
          </div>
        </div>
      </fieldset>
      <fieldset>
        <h3 class="headline">Where are the dumpsters?</h3>
        {{form.non_field_errors}}
        {{form.street_address|add_attrs:"placeholder:Street and number"}}
        <div class="ui-grid-b">
          <div class="ui-block-a">{{form.zip_code|add_attrs:"placeholder:ZIP code"}}</div>
          <div class="ui-block-b">{{form.city|add_attrs:"placeholder:City"}}</div>
          <div class="geolocation ui-block-c ui-nodisc-icon ui-alt-icon">
            <input class="geolocate" data-icon="location" data-theme="f" data-iconpos="notext" value="Find current position" type="button">
          </div>
        </div>
      </fieldset>
      <p class="ui-nodisc-icon"><input data-icon="check" type="submit" value="Send"></p>
    </form>
  </div>
</div>
{% endblock %}

dumpsteroverflow/templates/overflow_sent.html
{% extends "base.html" %}

{% block body %}
  {% if flash_error %}
    <div data-role="page" data-theme="a" data-dialog="true" data-close-btn="none" data-url="/overflow/0">
      <div data-role="header">
        <h1>Ouch!</h1>
      </div>

      <div role="main" class="ui-content">
        <p>{{ flash_error }}</p>
        <p class="s-btn-centered"><a href="/" class="ui-btn ui-btn-inline">OK</a></p>
      </div>
    </div>
  {% else %}
    <div data-role="page" data-theme="a" data-dialog="true" data-close-btn="none" data-url="/overflow/{{points}}">
      <div data-role="header">
        <h1>Thank you!</h1>
      </div>

      <div role="main" class="ui-content">
        <p>You just won {{points}} karma pts!</p>
        <p class="s-btn-centered"><a href="/" class="ui-btn ui-btn-inline">Great</a></p>
      </div>
    </div>
  {% endif %}
{% endblock %}